name: "Mitigate Injection"
inputs:
  your-name:
    description: "Your Name"
    required: true
runs:
  using: "composite"
  steps:
      - run: YOUR_NAME=${{ inputs.your-name }} # Beware to not enclose the context input with single or double quotes
        shell: bash

