name: Caching
on:
  push:
  #workflow_dispatch:
jobs:
  project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: new-cache
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/cache-key') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Echoing cache hit
        run: echo Cache hit ${{ steps.cache.outputs.cache-hit }}

      - run: ls -la ~/.cache

      - run: export DATE="$(date +'%Y-%m-%d_%H-%M-%S-%3N')-NO-HIT-PROJECT" && echo no hit && mkdir -p ~/.cache && echo $DATE > ~/.cache/$DATE   
        if: steps.cache.outputs.cache-hit != 'true'

      - run: export DATE="$(date +'%Y-%m-%d_%H-%M-%S-%3N')-ALWAYS-PROJECT" && echo always && mkdir -p ~/.cache && echo $DATE > ~/.cache/$DATE   
