name: Caching
on:
  #push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: kache
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/cache-key') }}
          #restore-keys: |
          #  ${{ runner.os }}-build-${{ env.cache-name }}-
          #  ${{ runner.os }}-build-
          #  ${{ runner.os }}-

      - name: Echoing cache hit
        run: echo Cache hit ${{ steps.cache.outputs.cache-hit }}

      - name: Echoing cache-key content
        run: cat cache-keys/cache-key

      - name: Echoing cache content before optionally filling it
        run: cat cache/date > cache/last-cached-content || true

      - name: Optionally fill cache
        run: '[ ${{ steps.cache.outputs.cache-hit }} ] || date > cache/last-cached-content'

      - name: Echoing cache content after optionally filling it
        run: cat cache/date > cache/last-cached-content || true

