name: Caching
on:
  #push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache
        id: cache
        uses: actions/cache@v2
        env:
          cache-name: kache
        with:
          path: ~/.cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/cache-key') }}
          #restore-keys: |
          #  ${{ runner.os }}-build-${{ env.cache-name }}-
          #  ${{ runner.os }}-build-
          #  ${{ runner.os }}-

      - name: Echoing key
        run: echo  ${{ runner.os }}-build-

      - name: Echoing cache hit
        run: Cache hit: ${{ steps.cache.outputs.cache-hit }
