name: Caching
on:
  push:
    branches: [test-env] 
  #workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test-env
    steps:
      - uses: actions/checkout@v2
      - run: echo Testing test-env environment
