name: IO Workflow
on:
  workflow_dispatch:
    inputs:
      who-to-greet:
        description: 'Person to greet'
        default: 'World'
        required: true
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
      shell: bash
    - uses: ./.github/actions/input-action # Do not override defaults in called action