name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #- uses: actions/setup-node@v2
      #  with:
      #    node-version: '14'
      #- run: npm install -g bats
      #- run: bats -v
      #- uses: getsentry/action-git-diff-suggestions@main
      #  with:
      #    message: 'Testing diff'
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '11'
      #- run: java -cp java HelloWorldApp
      - run: pwd
      - run: ls -la

