name: Mitigation 1
on:
  #push: 
  workflow_dispatch:
    inputs:
      your-name:
        required: true
        description: Your name
        default: 'a"; ls $GITHUB_WORKSPACE"'
  #pull_request:
jobs:
  inject-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/mitigation-action
        with:
          your-name: ${{ github.event.inputs.your-name }}
