name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@5c59dabdfd4dd5bd9c6e6d255b01b9d764af4414
        with:
          project: Zdoc Kanban
          column: In progress
          repo-token: ${{ secrets.GITHUB_TOKEN }}
