name: Move assigned card
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@bb266ff4dde9242060e2d5418e120a133586d488
        with:
          project: Zdoc Kanban
          column: In progress
          repo-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
