name: Receive PR

# read-only repo token
# no access to secrets
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:        
      - uses: actions/checkout@v2
      - run: ls -la
      - run: env | sort
      - run: echo owner - "${{ github.repository }}"
      - run: echo repo - "${{ github.repository_owner }}"

      # imitation of a build process
      - name: Build
        run: echo Build my app

      - name: Save PR number
        run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} > ./pr/NR
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: pr/