
name: Inject Workflow
on:
  #push: 
  workflow_dispatch:
    inputs:
      your_name:
        required: true
        description: Your name
        default: 'a"; ls $GITHUB_WORKSPACE"'
  #pull_request:
jobs:
  inject-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: YOUR_NAME="${{ github.event.inputs.your_name }}"
      #- run: title="${{ github.event.pull_request.title }}"
