name: Secrets Workflow
on:
  push: 
  #workflow_dispatch:
jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.THE_PASS}} 
      #- name: Retrieve repo secret
      #  env:
      #    secret: ${{ secrets.GENERAL_PASS }}
      #  run: echo "$secret" | rev
  #secret-env-job:
  #  runs-on: ubuntu-latest
  #  environment: test-env
  #  steps:
  #    - name: Retrieve repo secret
  #      env:
  #        secret: ${{ secrets.GENERAL_PASS }}
  #      run: echo "$secret" | rev
  #    - name: Retrieve repo env secret
  #      env:
  #        secret: ${{ secrets.TEST_ENV_PASS }}
  #      run: echo "$secret" | rev
