name: Secrets Workflow
on:
  #push: 
  workflow_dispatch:
jobs:
  secret-job:
    runs-on: ubuntu-latest
    steps:
      # Overrides Organization secret
      - run: "echo THE_PASS: ${{ secrets.THE_PASS}} | sed 's/pass$/xass/'"
      
      # Organization secret - Not defined at other levels
      - run: "echo ZOLATON_ORG_PASS: ${{ secrets.ZOLATON_ORG_PASS}} | sed 's/pass$/xass/'"

  secret-test-job:
    runs-on: ubuntu-latest
    environment: test
    steps:
      # Overrides Organization and repo secret
      - run: "echo THE_PASS: ${{ secrets.THE_PASS}} | sed 's/pass$/xass/'"
      
      # Environment secret - Not defined at other levels
      - run: "echo ZDOCS_TEST_PASS: ${{ secrets.ZDOCS_TEST_PASS}} | sed 's/pass$/xass/'"
      
      # Organization secret - Not defined at other levels
      - run: "echo ZOLATON_ORG_PASS: ${{ secrets.ZOLATON_ORG_PASS}} | sed 's/pass$/xass/'"

