name: Sharing Workflow
on:
  #push:
  workflow_dispatch:
jobs:
  uploading:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v2
        with:
          name: output-log-file
          path: output.log
  dowloading:
    runs-on: ubuntu-latest
    needs: uploading
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: output-log-file
      - run: cat output.log