name: Several Jobs
on:
  push: 
  #workflow_dispatch:
jobs:
  build-1:
    runs-on: ubuntu-latest
    steps:
      - run: echo build 1 step 1
      - run: echo build 1 step 2
  build-2:
    runs-on: ubuntu-latest
    steps:
      - run: echo build 2 step 1
      - run: echo build 2 step 2
  build-3:
    runs-on: ubuntu-latest
    steps:
      - run: echo build 3 step 1
      - run: echo build 3 step 2
  integration-1:
    runs-on: ubuntu-latest
    needs:   build-1
    steps:
      - run: echo integration 1 step 1
      - run: echo integration 1 step 2
      - run: echo integration 1 step 3
  integration-2:
    runs-on: ubuntu-latest
    needs:   build-2
    steps:
      - run: echo integration 2 step 1
